
GET http://localhost:7000/
###
GET http://localhost:7000/about
###
GET http://localhost:7000/tickets




### Get all animals
GET http://localhost:7000/animals
### Get specific animal
GET http://localhost:7000/animals/1
### Create new animal
POST http://localhost:7000/animals
Content-Type: application/json

{
  "name": "Lion",
  "count": 1
}
### Create another new animal
POST http://localhost:7000/animals
Content-Type: application/json

{
  "name": "Wolf",
  "count": 5
}

### Delete an animal
DELETE http://localhost:7000/animals/2

### UPDATE an animal
PATCH http://localhost:7000/animals/4
Content-Type: application/json

{
  "name": "Tiger",
  "count": 50
}



### Get all Sea Critters
GET http://localhost:7000/sea-critters
### Get specific Sea Critter
GET http://localhost:7000/sea-critters/1
### Create new Sea Critter
POST http://localhost:7000/sea-critters
Content-Type: application/json

{
  "name": "Ctenophora elegans",
  "count": 1
}
### Create another new Sea Critter
POST http://localhost:7000/sea-critters
Content-Type: application/json

{
  "name": "Nymphon residuum",
  "count": 5
}

### Delete anSea Critter
DELETE http://localhost:7000/sea-critters/2

### UPDATE a Sea Critter
PATCH http://localhost:7000/sea-critters/4
Content-Type: application/json

{
  "name": "Fangtooth",
  "count": 50
}
